### ISSUE TITLE
Request including our company (PT Pintu Kemana Saja)

### ISSUE THREAD

**Issue by tikaifp** [jackyef/id-wfa#10]
Hi Jacky!

Can you help us to include our company on this site? below is the detail of our opening job vacancy.

Link : https://careers.pintu.co.id/jobs

Opening Job Vacancy :
**Legal**
- Senior/Head of Government Relations : https://careers.pintu.co.id/jobs/1693839-senior-head-of-government-relations-officer
- Procurement Specialist : https://careers.pintu.co.id/jobs/1718553-procurement-specialist
- Senior/Head of Compliance : https://careers.pintu.co.id/jobs/1693746-senior-head-of-compliance
- Compliance Officer : https://careers.pintu.co.id/jobs/1699151-compliance-officer
- Government Relations : https://careers.pintu.co.id/jobs/1694584-government-relations

Marketing
- Community Manager : https://careers.pintu.co.id/jobs/1704749-community-manager
- Growth Marketing CRM Specialist : https://careers.pintu.co.id/jobs/1698419-growth-marketing-crm-specialist

People & Culture 
- Sr. Talent Acquisition and Employer Branding : https://careers.pintu.co.id/jobs/1668791-senior-talent-acquisition-and-employer-branding
- Talent Acquisition Intern : https://careers.pintu.co.id/jobs/1702867-talent-acquisition-intern

Finance
- Finance, Analyst  & Tax Analyst : https://careers.pintu.co.id/jobs/1694422-finance-accounting-tax-analyst
- Tax Analyst : https://careers.pintu.co.id/jobs/1694608-tax-analyst

Product 
- Product Marketing Specialist : https://careers.pintu.co.id/jobs/1696050-product-marketing-specialist
- Senior Business Analyst : https://careers.pintu.co.id/jobs/1683153-sr-business-analyst
- Product Manager : https://careers.pintu.co.id/jobs/1683151-product-manager

Design & Creative 
- Sr. UX Researcher : https://careers.pintu.co.id/jobs/1683156-sr-ux-researcher
- UX Writer : https://careers.pintu.co.id/jobs/1677611-ux-writer

Engineering 
- Associate Data Engineering : https://careers.pintu.co.id/jobs/1695407-associate-data-engineer
- Office Engineer : https://careers.pintu.co.id/jobs/1683154-office-engineer
-  Engineering Manager : https://careers.pintu.co.id/jobs/1674618-engineering-manager
- Software Development Engineer (Quality Process) : https://careers.pintu.co.id/jobs/1665992-software-development-engineer-quality-process
- Quality Assurance Engineer (Automation) /SDET : https://careers.pintu.co.id/jobs/1665987-quality-assurance-engineer-automation-sdet
- Site Reliability Engineer (DevOps/Infra) : https://careers.pintu.co.id/jobs/1663386-site-reliability-engineer-devops-infra
- Software Development Engineer : https://careers.pintu.co.id/jobs/1663236-software-development-engineer

Thank you !

![lambang pintu](https://user-images.githubusercontent.com/104187612/164638657-e58b8e21-c303-4670-96f4-11885c7bbd16.png)

**Comment by jackyef** [comment]
Hi 👋 
Thanks for the elaborate write-up 🙂 

Do all these departments allow WFA fully, as in not requiring to go into office at all permanently? 
If not, could you help listing down which departments that do? The website is supposed to only include jobs that allow WFA fully.

Thanks!

**Comment by tikaifp** [comment]
Hi Jacky, 

Of course, for all job vacancy we have implemented flexible work arrangements (You can work from the office, home, cafes or wherever you wish!)

**Comment by jackyef** [comment]
> Hi Jacky, 
> Of course, for all job vacancy we have implemented flexible work arrangements (You can work from the office, home, cafes or wherever you wish!)

I tried filtering for fully remote jobs and found nothing. Seems like most jobs are "hybrid remote", could you elaborate on that? 
![image](https://user-images.githubusercontent.com/7252454/164649079-9d604d46-e1df-4845-90bf-db1bd457fdf0.png)

**Comment by tikaifp** [comment]
I see, sure jacky. 

at Pintu we implement flexible work arrangements (which means you can work from the office, home, cafes or wherever you wish!). But I have changed the remote status from hybrid to fully remote. you can check!

**Comment by jackyef** [comment]
Awesome, thanks for fix! I'll be taking the job openings that are categorized as "Fully remote" from https://careers.pintu.co.id/jobs to be shown in this project 👍

**Comment by tikaifp** [comment]
Thanks Jacky for helping us ^^
