### ISSUE TITLE
Add Bobobox

### ISSUE THREAD

**Issue by yehezkielgunawan** [jackyef/id-wfa#4]
[https://glints.com/id/en/companies/pt-bobobox-mitra-indonesia/00e32ac6-95b0-4723-8dc2-f3a32f1d884d](https://glints.com/id/en/companies/pt-bobobox-mitra-indonesia/00e32ac6-95b0-4723-8dc2-f3a32f1d884d)

There is some job that is not explicitly written as a remote job (WFA) because it hasn't been updated yet by the HR team, but actually, Bobobox is WFA friendly (currently just for the tech & product team).

**Comment by jackyef** [comment]
I'll just include jobs in the "Design" and "Software Engineering" for now, is that okay?

**Comment by yehezkielgunawan** [comment]
Yep, it's okay
