### ISSUE TITLE
Save company logo images in repo

### ISSUE THREAD

**Issue by jackyef** [jackyef/id-wfa#6]
We are currently using external images for company logos (see [here](https://github.com/jackyef/id-wfa/blob/fc90d88244acb1384dab7ce76a4efd1dedf3999e/src/utils/dataSources/constants.ts#L4-L9))

This could be a problem if the image is no longer hosted there. We should download the images and store them in the repo (under `/public`) and refer to those instead.

**Comment by HridanshS** [comment]
I would like to take up this issue. I went to 
[id-wfa](https://github.com/jackyef/id-wfa)/public/
but I am unable to upload the files to it. I have already downloaded some of the logos and saved them as 'Pinhome.png' for instance

**Comment by HridanshS** [comment]
https://kerjabilitas.com/user_image/user2/logo_e5efdf1e26f4ef0117910b60ac764cca.jpg

This jpg is unavailable

**Comment by jackyef** [comment]
Hi, thanks for taking a look 👋 
Are you familiar with `git` workflow? Do you have `git` installed locally?

**Comment by HridanshS** [comment]
Hello,

I am not very familiar with git workflow but if you could guide me to an appropriate youtube video, I can understand it and follow the appropriate steps.
Thank you for your help.

**Comment by jackyef** [comment]
I see! Apologies, I don't think this is a good project to get started with `git`. I would point you to this [YouTube video](https://www.youtube.com/watch?v=8JJ101D3knE) to learn about it (I haven't watched it myself, but it does look pretty good!) :)
